name = "worker-sqs"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
[env.dev]
account_id = ""
route = ""
zone_id = ""

[env.dev.vars]
AWS_ACCOUNT_ID = ""
AWS_SQS_QUEUENAME = ""
AWS_DEFAULT_REGION = ""
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
